version: '3.9'

services:
  mongodb:
    image: mongo:7.0
    container_name: sw_mongo_dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securewealth123
      MONGO_INITDB_DATABASE: securewealth
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - sw_dev_network

volumes:
  mongo_data_dev:

networks:
  sw_dev_network:
    driver: bridge
